[workspace]
members = [

  # Secret Headstash Contract
  "contracts/cw-glob",
  "contracts/cw-ica-controller",
  "contracts/cw-ica-owner",
  # "scripts",
]
exclude = ["scripts"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
