---
version: "2.0"
services:
  local-secret:
    image: ghcr.io/scrtlabs/localsecret-gitpod:v1.15.0-beta.15
    expose:
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 9091
        as: 9091
        to:
          - global: true
      - port: 9090
        as: 9090
        to:
          - global: true
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 1317
        as: 1317
        to:
          - global: true
      - port: 3000
        as: 3000
        to:
          - global: false
      - port: 24000
        as: 24000
        to:
          - global: false
    command: /bin/sh -c
    args:
      - >-
        cd /home/gitpod/ && SCRT_SGX_STORAGE=/opt/secret/.sgx_secrets
        /home/gitpod/bootstrap_init.sh false &
                node /home/gitpod/faucet_server.js &
                tail -f /dev/null
profiles:
  compute:
    local-secret:
      resources:
        cpu:
          units: 2
        memory:
          size: 16gb
        storage:
          - size: 50Gi
  placement:
    dcloud:
      pricing:
        local-secret:
          denom: uakt
          amount: 100000
deployment:
  local-secret:
    dcloud:
      profile: local-secret
      count: 1
