[package]
name = "polytone"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "Core interfaces for Polytone Interchain accounts and queries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = "2.2.2"
cw-storage-plus = "2.0.0"
cosmwasm-std = { version = "2.2.2", features = ["staking"] }
thiserror = { version = "2.0.12" }
headstash-public = { path = "../headstash-public" }
