[package]
name = "polytone"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "Core interfaces for Polytone Interchain accounts and queries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
anybuf = "0.5.0"
cosmos-sdk-proto = { version = "0.27", default-features = false, features = ["cosmwasm", "std"] }
cosmwasm-std = { version = "2.2.2", features = ["staking"] }
thiserror = { version = "2.0.12" }