[package]
name = "headstash-public"
authors = [""]
description = "Core interfaces for Headstashes, used with non-secret network libraries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = "2.2.2"
cw-storage-plus = "2.0.0"
cw-orch = { version = "0.28.0", features=["daemon"] }
cosmwasm-std = { version = "2.2.2", features = ["staking"] }
thiserror = { version = "2.0.12" }
