[package]
name = "cw-orch-polytone"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://https://github.com/permissionlessweb/cw-headstash/public-crates"
rust-version = "1.67"
version = "1.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch = { version = "0.28.0", features=["daemon"] }
cw-orch-interchain = { version = "0.9.0", features = ["daemon"] }


headstash-public = { path = "../headstash-public"}
cosmwasm-std = { version = "2.2.2", features = ["stargate"] }
polytone-note = {  version = "1.1.0", path = "../../contracts/polytone/contracts/note", features=["interface"] }
polytone-proxy = { version = "1.1.0", path = "../../contracts/polytone/contracts/proxy", features=["interface"] }
polytone-voice  = { version = "1.1.0", path =  "../../contracts/polytone/contracts/voice", features=["interface"] }

[dev-dependencies]
anyhow = { version = "1.0.51" }