[package]
name = "polytone"
authors = ["ekez <ekez@withoutdoing.com>"]
description = "Core interfaces for Polytone Interchain accounts and queries."
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
secret-toolkit = { git = "https://github.com/SolarRepublic/secret-toolkit.git", default-features = false, features = ["permit", "storage", "viewing-key", "notification"] }
cosmwasm-std = { workspace = true , features = ["ibc3"]}
# cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
