[package]
name = "headstash-scripts"
version = "0.1.0"
authors = ["TerpNETFoundation"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[features]


[dependencies]
tokio = "1.40.0"
anybuf =  "0.5.0"
anyhow =  "1.0.87"
reqwest = "0.12.7"
clap = { version = "4.5.0", features = ["derive"] }
log = "0.4.22"
# cosmos specific deps
cw-ica-controller = { git = "https://github.com/permissionlessweb/cw-ica-controller" , default-features = false }
cw-orch = {version = "0.25.0", features = ["daemon"]}
cosmrs = "0.19.0"
cosmwasm-std = { version = "2.1.3", default-features = false,features = [
  "stargate",
] }